name: LavaCrates
version: 1.2
main: hu.bNoli1.lavacrates.LavaCrates
api-version: 1.20
author: bNoli1
description: Egyedi láda nyitó plugin 1.20.4 szerverekre.
commands:
  lavacrates:
    description: A plugin főparancsa.
    aliases: [lc, crate]
    permission: lavacrates.admin
permissions:
  lavacrates.admin:
    description: Jogosultság a ládák kezeléséhez.
    default: op
